### ISSUE TITLE
Contrast levels are all over the place

### ISSUE THREAD

**Issue by Nergus** [OldUnreal/Unreal-testing#362]
When I launched the first level of the game, it seemed like the lighting was too bright compared to what I remember from the PC version. I don't know what are the settings to change this.

**Comment by Wooloomooloo2** [comment]
Remember to remove UWindowFonts.utx from the texture folder, otherwise it will be a mess.

**Comment by Nergus** [comment]
> Remember to remove UWindowFonts.utx from the texture folder, otherwise it will be a mess.

I did, but I realised it mostly had to do with the renderer.

**Comment by stijn-volckaert** [comment]
This is intentional. The mac patch sets the brightness setting to its maximum value by default, but you can change this in the settings menu.

The metal renderer also applies gamma correction. You cannot disable gamma correction currently, but you can reduce its strength by setting GammaOffset to a negative value in the [FruCoRe.FruCoReRenderDevice] section of ~/Library/Application Support/Unreal/System/UnrealOSX.ini.
